"""Structured output models for the temporal simulator.

Safety enforcement: coaching and feedback events use restricted content
policy — no free-text body, no evaluative language. Content is rendered
from structural fields (date, participant, topics, action items) only.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

# Workflow types where body content is prohibited (management_safety axiom)
_RESTRICTED_TYPES = frozenset({"coaching_note", "feedback"})

# Workflow types that generate significant downstream events
_SIGNIFICANT_TYPES = frozenset({"incident", "review_cycle"})


class ContentPolicy:
    """Safety boundary for simulated event content."""

    @staticmethod
    def is_restricted(workflow_type: str) -> bool:
        """Return True if this workflow type prohibits free-text body."""
        return workflow_type in _RESTRICTED_TYPES

    @staticmethod
    def allows_body(workflow_type: str) -> bool:
        """Return True if this workflow type can have body_template content."""
        return workflow_type not in _RESTRICTED_TYPES


class SimulatedEvent(BaseModel):
    """A single filesystem event generated by the simulator.

    For restricted types (coaching, feedback), body_template must be None.
    Content is generated from structural fields via templates.
    """

    date: str = Field(description="ISO date of the event (YYYY-MM-DD)")
    workflow_type: str = Field(description="Key into workflow-semantics.yaml")
    subdirectory: str = Field(description="Target subdirectory in DATA_DIR")
    filename: str = Field(description="Output filename")
    participant: str | None = Field(default=None, description="Person for people-related events")
    topics: list[str] = Field(default_factory=list, description="Structural content topics")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Frontmatter fields")
    body_template: str | None = Field(
        default=None,
        description="Body content template (only for unrestricted types)",
    )


class TickResult(BaseModel):
    """Result of processing a single simulation tick (one workday)."""

    date: str = Field(description="ISO date of this tick")
    events: list[SimulatedEvent] = Field(default_factory=list)
    checkpoint_ran: bool = Field(default=False)
    checkpoint_type: str | None = Field(default=None, description="'weekly' or 'significant'")

    @property
    def has_significant_events(self) -> bool:
        """True if this tick produced incidents or review cycles."""
        return any(e.workflow_type in _SIGNIFICANT_TYPES for e in self.events)
