# shared/axiom_precedents.py
"""Qdrant-backed precedent database for axiom enforcement.

Stores accumulated axiom-application decisions (case law). Each precedent
records a situation, the axiom it relates to, the decision made, and the
reasoning. Semantic search finds relevant precedents for new situations.

Authority hierarchy (vertical stare decisis):
  - operator (1.0): Operator explicitly decided. Highest authority.
  - agent (0.7): Agent decided at runtime. Pending operator review.
  - derived (0.5): Generated by derivation pipeline. Lowest authority.

Usage:
    from shared.axiom_precedents import PrecedentStore, Precedent

    store = PrecedentStore()
    store.ensure_collection()

    # Search for relevant precedents
    results = store.search("single_user", "adding OAuth2 for API access")

    # Record a new precedent
    store.record(Precedent(...))
"""

from __future__ import annotations

import json
import logging
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import TYPE_CHECKING

import yaml

from shared.config import get_qdrant

if TYPE_CHECKING:
    from pathlib import Path

log = logging.getLogger(__name__)

COLLECTION = "axiom-precedents"
VECTOR_DIM = 768

AUTHORITY_WEIGHTS = {
    "operator": 1.0,
    "agent": 0.7,
    "derived": 0.5,
}


@dataclass
class Precedent:
    id: str
    axiom_id: str
    situation: str
    decision: str  # "compliant" | "violation" | "edge_case"
    reasoning: str
    tier: str  # "T0" | "T1" | "T2" | "T3"
    distinguishing_facts: list[str]
    authority: str  # "operator" | "agent" | "derived"
    created: str
    superseded_by: str | None = None


class PrecedentStore:
    def __init__(self):
        self.client = get_qdrant()

    def ensure_collection(self) -> None:
        """Create the axiom-precedents collection if it doesn't exist."""
        from qdrant_client.models import Distance, VectorParams

        collections = [c.name for c in self.client.get_collections().collections]
        if COLLECTION not in collections:
            self.client.create_collection(
                COLLECTION,
                vectors_config=VectorParams(size=VECTOR_DIM, distance=Distance.COSINE),
            )
            log.info("Created Qdrant collection: %s", COLLECTION)

    def _generate_id(self) -> str:
        """Generate a unique precedent ID."""
        ts = datetime.now(UTC).strftime("%Y%m%d")
        short = uuid.uuid4().hex[:6]
        return f"PRE-{ts}-{short}"

    def _to_payload(self, precedent: Precedent) -> dict:
        """Convert a Precedent to a Qdrant payload dict."""
        return {
            "precedent_id": precedent.id,
            "axiom_id": precedent.axiom_id,
            "situation": precedent.situation,
            "decision": precedent.decision,
            "reasoning": precedent.reasoning,
            "tier": precedent.tier,
            "distinguishing_facts": json.dumps(precedent.distinguishing_facts),
            "authority": precedent.authority,
            "created": precedent.created,
            "superseded_by": precedent.superseded_by or "",
        }

    def _from_payload(self, point_id: str | object, payload: dict | None) -> Precedent:
        """Convert a Qdrant payload back to a Precedent."""
        if payload is None:
            payload = {}
        facts = payload.get("distinguishing_facts", "[]")
        if isinstance(facts, str):
            try:
                facts = json.loads(facts)
            except json.JSONDecodeError:
                facts = [facts] if facts else []
        return Precedent(
            id=payload.get("precedent_id", str(point_id)),
            axiom_id=payload.get("axiom_id", ""),
            situation=payload.get("situation", ""),
            decision=payload.get("decision", ""),
            reasoning=payload.get("reasoning", ""),
            tier=payload.get("tier", "T2"),
            distinguishing_facts=facts,
            authority=payload.get("authority", "derived"),
            created=payload.get("created", ""),
            superseded_by=payload.get("superseded_by") or None,
        )

    def search(
        self,
        axiom_id: str,
        situation: str,
        *,
        limit: int = 5,
    ) -> list[Precedent]:
        """Semantic search for precedents relevant to a situation."""
        from qdrant_client.models import FieldCondition, Filter, MatchValue

        from shared.config import embed

        query_vec = embed(situation, prefix="search_query")

        query_filter = Filter(
            must=[
                FieldCondition(key="axiom_id", match=MatchValue(value=axiom_id)),
                FieldCondition(key="superseded_by", match=MatchValue(value="")),
            ]
        )

        results = self.client.query_points(
            COLLECTION,
            query=query_vec,
            query_filter=query_filter,
            limit=limit,
        )

        return [self._from_payload(p.id, p.payload) for p in results.points]

    def record(self, precedent: Precedent) -> str:
        """Record a new precedent. Returns the precedent ID."""
        from qdrant_client.models import PointStruct

        from shared.config import embed

        if not precedent.id:
            precedent.id = self._generate_id()
        if not precedent.created:
            precedent.created = datetime.now(UTC).isoformat()

        vec = embed(precedent.situation, prefix="search_document")
        point_id = str(uuid.uuid5(uuid.NAMESPACE_DNS, f"axiom-precedent-{precedent.id}"))

        self.client.upsert(
            COLLECTION,
            [PointStruct(id=point_id, vector=vec, payload=self._to_payload(precedent))],
        )

        log.info(
            "Recorded precedent %s (axiom=%s, decision=%s)",
            precedent.id,
            precedent.axiom_id,
            precedent.decision,
        )
        return precedent.id

    def load_seeds(self, axioms_path: Path) -> int:
        """Load seed precedents from YAML files. Skips already-present IDs."""
        seed_dir = axioms_path / "precedents" / "seed"
        if not seed_dir.exists():
            return 0

        count = 0
        for seed_file in sorted(seed_dir.glob("*-seeds.yaml")):
            seeds = self._parse_seed_file(seed_file)
            for seed in seeds:
                self.record(seed)
                count += 1

        log.info("Loaded %d seed precedents from %s", count, seed_dir)
        return count

    def _parse_seed_file(self, path: Path) -> list[Precedent]:
        """Parse a seed YAML file into Precedent objects.

        Supports both formats:
        - Top-level axiom_id applied to all entries (original format)
        - Per-entry axiom_id overrides top-level (mixed-axiom files)
        """
        data = yaml.safe_load(path.read_text())
        default_axiom_id = data.get("axiom_id", "")
        precedents = []
        for entry in data.get("precedents", []):
            precedents.append(
                Precedent(
                    id=entry["id"],
                    axiom_id=entry.get("axiom_id", default_axiom_id),
                    situation=entry.get("situation", ""),
                    decision=entry.get("decision", ""),
                    reasoning=entry.get("reasoning", ""),
                    tier=entry.get("tier", "T2"),
                    distinguishing_facts=entry.get("distinguishing_facts", []),
                    authority=entry.get("authority", "derived"),
                    created=entry.get("created", ""),
                    superseded_by=None,
                )
            )
        return precedents

    def get_by_axiom(self, axiom_id: str, *, limit: int = 20) -> list[Precedent]:
        """Get all precedents for an axiom, sorted by authority then date."""
        from qdrant_client.models import FieldCondition, Filter, MatchValue

        query_filter = Filter(
            must=[
                FieldCondition(key="axiom_id", match=MatchValue(value=axiom_id)),
                FieldCondition(key="superseded_by", match=MatchValue(value="")),
            ]
        )

        results = self.client.scroll(
            COLLECTION,
            scroll_filter=query_filter,
            limit=limit,
        )

        precedents = [self._from_payload(p.id, p.payload) for p in results[0]]
        authority_order = {"operator": 0, "agent": 1, "derived": 2}
        precedents.sort(key=lambda p: (authority_order.get(p.authority, 9), p.created))
        return precedents

    def get_pending_review(self, *, limit: int = 20) -> list[Precedent]:
        """Get agent-created precedents awaiting operator review."""
        from qdrant_client.models import FieldCondition, Filter, MatchValue

        query_filter = Filter(
            must=[
                FieldCondition(key="authority", match=MatchValue(value="agent")),
                FieldCondition(key="superseded_by", match=MatchValue(value="")),
            ]
        )

        results = self.client.scroll(
            COLLECTION,
            scroll_filter=query_filter,
            limit=limit,
        )

        return [self._from_payload(p.id, p.payload) for p in results[0]]

    def promote(self, precedent_id: str) -> None:
        """Promote an agent precedent to operator authority."""
        from qdrant_client.models import FieldCondition, Filter, MatchValue, PointStruct

        results = self.client.scroll(
            COLLECTION,
            scroll_filter=Filter(
                must=[
                    FieldCondition(key="precedent_id", match=MatchValue(value=precedent_id)),
                ]
            ),
            limit=1,
        )

        if results[0]:
            point = results[0][0]
            payload: dict[str, object] = dict(point.payload or {})
            payload["authority"] = "operator"
            self.client.upsert(
                COLLECTION,
                [PointStruct(id=point.id, vector=point.vector, payload=payload)],  # type: ignore[arg-type]  # qdrant SDK VectorStructOutput vs VectorStruct mismatch
            )
            log.info("Promoted precedent %s to operator authority", precedent_id)

    def supersede(self, old_id: str, new_precedent: Precedent) -> str:
        """Supersede an existing precedent with a new one."""
        from qdrant_client.models import FieldCondition, Filter, MatchValue, PointStruct

        # Find old precedent
        results = self.client.scroll(
            COLLECTION,
            scroll_filter=Filter(
                must=[
                    FieldCondition(key="precedent_id", match=MatchValue(value=old_id)),
                ]
            ),
            limit=1,
        )

        new_id = self.record(new_precedent)

        if results[0]:
            point = results[0][0]
            payload: dict[str, object] = dict(point.payload or {})
            payload["superseded_by"] = new_id
            self.client.upsert(
                COLLECTION,
                [PointStruct(id=point.id, vector=point.vector, payload=payload)],  # type: ignore[arg-type]  # qdrant SDK VectorStructOutput vs VectorStruct mismatch
            )

        log.info("Superseded precedent %s with %s", old_id, new_id)
        return new_id
